version: '3.8'
services:




#------------------------ voyantis Server ---------------------------    
  voyantis:
    container_name: voyantis
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    restart: unless-stopped
    ports:
      - 80:80